/*
 * ClydeFrame.java
 *
 * Created on 29/01/2011, 10:20:22 AM
 */
package com.bradmcevoy.web.manage.gui;

import com.bradmcevoy.http.Request;
import com.bradmcevoy.http.Response;
import com.bradmcevoy.web.manage.logging.JTableLogger;
import com.ettrema.cache.Cache;
import com.ettrema.context.RootContext;
import com.ettrema.event.EventManager;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author brad
 */
public class ClydeFrame extends javax.swing.JFrame {

    private static ClydeFrame theInstance;
    private final JTableLogger tableLogger;
    private final RequestsTableModel requestModel;
    private final RootContext rootContext;
    private List<Cache> caches;

    /** Creates new form ClydeFrame */
    public ClydeFrame(RootContext rootContext, EventManager eventManager) {
        this.rootContext = rootContext;
        initComponents();
        tableLogger = new JTableLogger(tblLogs);
        this.setVisible(true);
        requestModel = new RequestsTableModel(eventManager);
        tblRequests.setModel(requestModel);
        Executors.newScheduledThreadPool(1).scheduleWithFixedDelay(new Runnable() {

            public void run() {
                updateScreen();
            }
        }, 1000, 1000, TimeUnit.MILLISECONDS);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        pnlSummary = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        scrollLogs = new javax.swing.JScrollPane();
        tblLogs = new javax.swing.JTable();
        scrollRequests = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStats = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTools = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabMain.setName("tabMain"); // NOI18N

        pnlSummary.setName("pnlSummary"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(ClydeFrame.class, this);
        jButton1.setAction(actionMap.get("doShutdown")); // NOI18N
        jButton1.setText("Shutdown");
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout pnlSummaryLayout = new javax.swing.GroupLayout(pnlSummary);
        pnlSummary.setLayout(pnlSummaryLayout);
        pnlSummaryLayout.setHorizontalGroup(
            pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSummaryLayout.createSequentialGroup()
                    .addGap(0, 144, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 145, Short.MAX_VALUE)))
        );
        pnlSummaryLayout.setVerticalGroup(
            pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
            .addGroup(pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSummaryLayout.createSequentialGroup()
                    .addGap(0, 114, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(0, 113, Short.MAX_VALUE)))
        );

        tabMain.addTab("Summary", pnlSummary);

        scrollLogs.setName("scrollLogs"); // NOI18N

        tblLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source", "Priority", "Line", "Message"
            }
        ));
        tblLogs.setName("tblLogs"); // NOI18N
        scrollLogs.setViewportView(tblLogs);

        tabMain.addTab("Logging", scrollLogs);

        scrollRequests.setName("scrollRequests"); // NOI18N

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Method", "Host", "User", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRequests.setName("tblRequests"); // NOI18N
        tblRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequestsMouseClicked(evt);
            }
        });
        scrollRequests.setViewportView(tblRequests);
        tblRequests.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblRequests.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblRequests.getColumnModel().getColumn(2).setPreferredWidth(100);

        tabMain.addTab("Requests", scrollRequests);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Value"
            }
        ));
        tblStats.setName("tblStats"); // NOI18N
        jScrollPane1.setViewportView(tblStats);

        tabMain.addTab("Stats", jScrollPane1);

        getContentPane().add(tabMain, java.awt.BorderLayout.CENTER);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        mnuTools.setText("Tools");
        mnuTools.setName("mnuTools"); // NOI18N

        jMenuItem1.setAction(actionMap.get("doClear")); // NOI18N
        jMenuItem1.setText("Clear");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        mnuTools.add(jMenuItem1);

        jMenuBar1.add(mnuTools);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestsMouseClicked
        if (evt.getClickCount() == 2) {
            SwingUtilities.invokeLater(new Runnable() {

                public void run() {
                    int row = tblRequests.getSelectedRow();
                    Request request = requestModel.getRequest(row);
                    Response response = requestModel.getResponse(row);
                    NewJDialog requestPanel = new NewJDialog(theInstance, true, request, response);
                    requestPanel.setLocation(100, 100);
                    requestPanel.setSize(400, 600);
                    requestPanel.setVisible(true);
//                    NewJDialog dialog = new NewJDialog(ClydeFrame.theInstance, true);
//                    dialog.setVisible(true);

                }
            });
        }

    }//GEN-LAST:event_tblRequestsMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JPanel pnlSummary;
    private javax.swing.JScrollPane scrollLogs;
    private javax.swing.JScrollPane scrollRequests;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tblLogs;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTable tblStats;
    // End of variables declaration//GEN-END:variables

    public JTable getTblLogs() {
        return tblLogs;
    }

    private void updateScreen() {
        if (caches == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblStats.getModel();
        model.setRowCount(0);
        for (Cache cache : caches) {
            model.addRow(new Object[]{cache.getName() + " Hits", cache.getHits()});
            model.addRow(new Object[]{cache.getName() + " Misses", cache.getMisses()});
        }
        model.fireTableDataChanged();
    }

    public List<Cache> getCaches() {
        return caches;
    }

    public void setCaches(List<Cache> caches) {
        this.caches = caches;
    }

    @Action
    public void doShutdown() {
        rootContext.shutdown();
        System.exit(1);
    }

    @Action
    public void doClear() {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                requestModel.clearAll();
                tableLogger.clearAll();
            }
        });
    }
}
