/*
 * ClydeFrame.java
 *
 * Created on 29/01/2011, 10:20:22 AM
 */
package com.ettrema.web.manage.gui;

import com.bradmcevoy.http.Request;
import com.bradmcevoy.http.Response;
import com.ettrema.web.manage.logging.JTableLogger;
import com.ettrema.web.manage.synch.FileWatcher;
import com.ettrema.cache.Cache;
import com.ettrema.context.RootContext;
import com.ettrema.event.EventManager;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author brad
 */
public class ClydeFrame extends javax.swing.JFrame {

    private static ClydeFrame theInstance;
    private final JTableLogger tableLogger;
    private final RequestsTableModel requestModel;
    private final RootContext rootContext;
    private final List<FileWatcher> fileWatchers;
    private List<Cache> caches;

    /** Creates new form ClydeFrame */
    public ClydeFrame(RootContext rootContext, EventManager eventManager, List<FileWatcher> fileWatchers) {
        this.rootContext = rootContext;
        initComponents();
        tableLogger = new JTableLogger(tblLogs);
        this.setVisible(true);
        requestModel = new RequestsTableModel(eventManager);
        tblRequests.setModel(requestModel);
        this.fileWatchers = Collections.unmodifiableList(fileWatchers);

        Executors.newScheduledThreadPool(1).scheduleWithFixedDelay(new Runnable() {

            public void run() {
                updateScreen();
            }
        }, 1000, 1000, TimeUnit.MILLISECONDS);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        scrollLogs = new javax.swing.JScrollPane();
        tblLogs = new javax.swing.JTable();
        scrollRequests = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStats = new javax.swing.JTable();
        pnlSummary = new javax.swing.JPanel();
        btnShutdown = new javax.swing.JButton();
        btnScan = new javax.swing.JButton();
        btnClearCaches = new javax.swing.JButton();
        btnGc = new javax.swing.JButton();
        btnScan1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTools = new javax.swing.JMenu();
        mnuClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabMain.setName("tabMain"); // NOI18N

        scrollLogs.setName("scrollLogs"); // NOI18N

        tblLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Priority", "Source", "Message"
            }
        ));
        tblLogs.setName("tblLogs"); // NOI18N
        scrollLogs.setViewportView(tblLogs);

        tabMain.addTab("Logging", scrollLogs);

        scrollRequests.setName("scrollRequests"); // NOI18N

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Method", "Host", "User", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRequests.setName("tblRequests"); // NOI18N
        tblRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequestsMouseClicked(evt);
            }
        });
        scrollRequests.setViewportView(tblRequests);
        tblRequests.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblRequests.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblRequests.getColumnModel().getColumn(2).setPreferredWidth(100);

        tabMain.addTab("Requests", scrollRequests);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Value"
            }
        ));
        tblStats.setName("tblStats"); // NOI18N
        jScrollPane1.setViewportView(tblStats);

        tabMain.addTab("Stats", jScrollPane1);

        pnlSummary.setName("pnlSummary"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(ClydeFrame.class, this);
        btnShutdown.setAction(actionMap.get("doShutdown")); // NOI18N
        btnShutdown.setText("Shutdown");
        btnShutdown.setName("btnShutdown"); // NOI18N

        btnScan.setAction(actionMap.get("doScan")); // NOI18N
        btnScan.setText("Scan for new files");
        btnScan.setName("btnScan"); // NOI18N

        btnClearCaches.setAction(actionMap.get("doClearCache")); // NOI18N
        btnClearCaches.setText("Clear Caches");
        btnClearCaches.setName("btnClearCaches"); // NOI18N

        btnGc.setAction(actionMap.get("doGc")); // NOI18N
        btnGc.setText("GC (compact memory)");
        btnGc.setName("btnGc"); // NOI18N

        btnScan1.setAction(actionMap.get("doReload")); // NOI18N
        btnScan1.setText("Reload all files");
        btnScan1.setName("btnScan1"); // NOI18N

        javax.swing.GroupLayout pnlSummaryLayout = new javax.swing.GroupLayout(pnlSummary);
        pnlSummary.setLayout(pnlSummaryLayout);
        pnlSummaryLayout.setHorizontalGroup(
            pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSummaryLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShutdown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnGc, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnClearCaches, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnScan1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnScan, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );
        pnlSummaryLayout.setVerticalGroup(
            pnlSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSummaryLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnShutdown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnScan)
                .addGap(11, 11, 11)
                .addComponent(btnScan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearCaches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGc)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tabMain.addTab("Control", pnlSummary);

        getContentPane().add(tabMain, java.awt.BorderLayout.CENTER);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        mnuTools.setText("Tools");
        mnuTools.setName("mnuTools"); // NOI18N

        mnuClear.setAction(actionMap.get("doClear")); // NOI18N
        mnuClear.setName("mnuClear"); // NOI18N
        mnuTools.add(mnuClear);

        jMenuBar1.add(mnuTools);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestsMouseClicked
        if (evt.getClickCount() == 2) {
            SwingUtilities.invokeLater(new Runnable() {

                public void run() {
                    int row = tblRequests.getSelectedRow();
                    Request request = requestModel.getRequest(row);
                    Response response = requestModel.getResponse(row);
                    NewJDialog requestPanel = new NewJDialog(theInstance, true, request, response);
                    requestPanel.setLocation(100, 100);
                    requestPanel.setSize(400, 600);
                    requestPanel.setVisible(true);
//                    NewJDialog dialog = new NewJDialog(ClydeFrame.theInstance, true);
//                    dialog.setVisible(true);

                }
            });
        }

    }//GEN-LAST:event_tblRequestsMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCaches;
    private javax.swing.JButton btnGc;
    private javax.swing.JButton btnScan;
    private javax.swing.JButton btnScan1;
    private javax.swing.JButton btnShutdown;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuClear;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JPanel pnlSummary;
    private javax.swing.JScrollPane scrollLogs;
    private javax.swing.JScrollPane scrollRequests;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTable tblLogs;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTable tblStats;
    // End of variables declaration//GEN-END:variables

    public JTable getTblLogs() {
        return tblLogs;
    }

    private void updateScreen() {
        if (caches == null) {
            return;
        }
        try {
            DefaultTableModel model = (DefaultTableModel) tblStats.getModel();
            model.setRowCount(0);
            for (Cache cache : caches) {
                model.addRow(new Object[]{cache.getName() + " Hits", cache.getHits()});
                model.addRow(new Object[]{cache.getName() + " Misses", cache.getMisses()});
                model.addRow(new Object[]{cache.getName() + " Size", cache.getSize()});
            }
            long freeMem = Runtime.getRuntime().freeMemory();
            long maxMem = Runtime.getRuntime().maxMemory();
            long totalMem = Runtime.getRuntime().totalMemory();
            model.addRow(new Object[]{"Free mem", formatBytes(freeMem)});
            model.addRow(new Object[]{"Max mem", formatBytes(maxMem)});
            model.addRow(new Object[]{"Total mem", formatBytes(totalMem)});
            model.fireTableDataChanged();
        } catch (Throwable e) {
            System.out.println("error processing caches");
            e.printStackTrace();
        }
    }

    public static String formatBytes(Long n) {
        if (n == null) {
            return "Unknown";
        } else if (n < 1000) {
            return n + " bytes";
        } else if (n < 1000000) {
            return n / 1000 + "KB";
        } else if (n < 1000000000) {
            return n / 1000000 + "MB";
        } else {
            return n / 1000000000 + "GB";
        }
    }

    public List<Cache> getCaches() {
        return caches;
    }

    public void setCaches(List<Cache> caches) {
        this.caches = caches;
    }

    @Action
    public void doShutdown() {
        rootContext.shutdown();
        System.exit(1);
    }

    @Action
    public void doClear() {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                requestModel.clearAll();
                tableLogger.clearAll();
            }
        });
    }

    @Action
    public void doScan() {
        System.out.println("doScan");
        Thread t = new Thread(new Runnable() {

            @Override
            public void run() {
                System.out.println("beginning scan");
                for (FileWatcher fileWatcher : fileWatchers) {
                    try {
                        fileWatcher.forceReload();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
        t.start();
    }

    @Action
    public void doClearCache() {
        for (Cache c : caches) {
            c.flush();
        }
    }

    @Action
    public void doGc() {
        System.gc();
    }

    @Action
    public void doReload() {
        System.out.println("doScan");
        Thread t = new Thread(new Runnable() {

            @Override
            public void run() {
                System.out.println("beginning scan");
                for (FileWatcher fileWatcher : fileWatchers) {
                    try {
                        fileWatcher.forceReload();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
        t.start();
    }
}
