/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 1/02/2011, 3:05:55 PM
 */

package com.ettrema.web.manage.gui;

import com.bradmcevoy.http.Request;
import com.bradmcevoy.http.Response;
import java.util.Map.Entry;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brad
 */
public class NewJDialog extends javax.swing.JDialog {

    private final Request request;
    private final Response response;

    /** Creates new form NewJDialog */
    public NewJDialog(java.awt.Frame parent, boolean modal, Request request, Response response) {
        super(parent, modal);
        this.request = request;
        this.response = response;

        initComponents();
        DefaultTableModel model = (DefaultTableModel) tblForm.getModel();
        for (Entry<String, String> entry : request.getParams().entrySet()) {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
        model = (DefaultTableModel) tblHeadersRequest.getModel();
        for (Entry<String, String> entry : request.getHeaders().entrySet()) {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
        if (response != null) {
            model = (DefaultTableModel) tblHeadersResponse.getModel();
            for (Entry<String, String> entry : response.getHeaders().entrySet()) {
                model.addRow(new Object[]{entry.getKey(), entry.getValue()});
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblForm = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHeadersRequest = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHeadersResponse = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form parameters"));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Value"
            }
        ));
        tblForm.setName("tblForm"); // NOI18N
        jScrollPane1.setViewportView(tblForm);

        getContentPane().add(jScrollPane1);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Request headers"));
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblHeadersRequest.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblHeadersRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Header", "Value"
            }
        ));
        tblHeadersRequest.setName("tblHeadersRequest"); // NOI18N
        jScrollPane2.setViewportView(tblHeadersRequest);

        getContentPane().add(jScrollPane2);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Response Headers"));
        jScrollPane3.setName("jScrollPane3"); // NOI18N

        tblHeadersResponse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Header", "Value"
            }
        ));
        tblHeadersResponse.setName("tblHeadersResponse"); // NOI18N
        jScrollPane3.setViewportView(tblHeadersResponse);

        getContentPane().add(jScrollPane3);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblForm;
    private javax.swing.JTable tblHeadersRequest;
    private javax.swing.JTable tblHeadersResponse;
    // End of variables declaration//GEN-END:variables

}
